# SPDX-FileCopyrightText: 2026 Jinghao Hu
# SPDX-License-Identifier: MIT

"""Multiplicative seasonal STARIMA estimation."""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy import stats
from scipy.optimize import OptimizeResult, least_squares

from pystarmax._validation import (
    FloatArray,
    validate_nonnegative_int,
    validate_time_space,
)
from pystarmax.differencing import (
    CombinedDifferencingState,
    combined_difference,
)
from pystarmax.models.starma import STARMA
from pystarmax.results import STARMAResult
from pystarmax.seasonal import (
    LagOperator,
    expand_multiplicative_operators,
    maximum_operator_lag,
)
from pystarmax.weights import SpatialWeights, coerce_weights


class SeasonalSTARIMA:
    """Fit a multiplicative seasonal space-time ARIMA model.

    The stationary transformed process follows

    ``Phi_s(B**s) phi(B) w_t = Theta_s(B**s) theta(B) epsilon_t``

    with ``w_t = (1-B)^d (1-B**s)^D z_t``. Ordinary and seasonal
    autoregressive/moving-average factors are parameterized separately. Their
    cross-lag coefficients are generated by matrix multiplication and parameter
    products rather than estimated as independent free coefficients.

    Parameters
    ----------
    ar_order, integration_order, ma_order:
        Ordinary orders ``(p, d, q)``.
    seasonal_ar_order, seasonal_integration_order, seasonal_ma_order:
        Seasonal orders ``(P, D, Q)``.
    seasonal_period:
        Positive seasonal period ``s``.
    include_intercept:
        Include a common intercept on the highest-difference scale.
    max_iter:
        Maximum nonlinear objective evaluations when seasonal AR or MA factors
        are present.
    tol:
        Shared ``ftol``, ``xtol``, and ``gtol`` convergence tolerance.
    ridge:
        Optional L2 penalty on all factor coefficients except the intercept.
    """

    def __init__(
        self,
        ar_order: int = 1,
        integration_order: int = 0,
        ma_order: int = 0,
        *,
        seasonal_ar_order: int = 0,
        seasonal_integration_order: int = 1,
        seasonal_ma_order: int = 0,
        seasonal_period: int = 12,
        include_intercept: bool = True,
        max_iter: int = 1000,
        tol: float = 1e-8,
        ridge: float = 0.0,
    ) -> None:
        self.ar_order = validate_nonnegative_int(ar_order, name="ar_order")
        self.integration_order = validate_nonnegative_int(
            integration_order, name="integration_order"
        )
        self.ma_order = validate_nonnegative_int(ma_order, name="ma_order")
        self.seasonal_ar_order = validate_nonnegative_int(
            seasonal_ar_order, name="seasonal_ar_order"
        )
        self.seasonal_integration_order = validate_nonnegative_int(
            seasonal_integration_order, name="seasonal_integration_order"
        )
        self.seasonal_ma_order = validate_nonnegative_int(
            seasonal_ma_order, name="seasonal_ma_order"
        )
        self.seasonal_period = validate_nonnegative_int(
            seasonal_period, name="seasonal_period"
        )
        if self.seasonal_period == 0:
            raise ValueError("seasonal_period must be positive")
        if not any(
            (
                self.ar_order,
                self.ma_order,
                self.seasonal_ar_order,
                self.seasonal_ma_order,
            )
        ):
            raise ValueError("at least one AR or MA order must be positive")
        self.include_intercept = bool(include_intercept)
        self.max_iter = validate_nonnegative_int(max_iter, name="max_iter")
        if self.max_iter == 0:
            raise ValueError("max_iter must be positive")
        if tol <= 0:
            raise ValueError("tol must be positive")
        if ridge < 0:
            raise ValueError("ridge must be non-negative")
        self.tol = float(tol)
        self.ridge = float(ridge)

        self.result_: STARMAResult | None = None
        self.optimization_result_: OptimizeResult | None = None
        self.core_model_: STARMA | None = None
        self.weights_: SpatialWeights | None = None
        self.data_: FloatArray | None = None
        self.transformed_data_: FloatArray | None = None
        self.differencing_state_: CombinedDifferencingState | None = None
        self._internal_residuals: FloatArray | None = None

    @property
    def order(self) -> tuple[int, int, int]:
        """Ordinary order tuple ``(p, d, q)``."""
        return self.ar_order, self.integration_order, self.ma_order

    @property
    def seasonal_order(self) -> tuple[int, int, int, int]:
        """Seasonal order tuple ``(P, D, Q, s)``."""
        return (
            self.seasonal_ar_order,
            self.seasonal_integration_order,
            self.seasonal_ma_order,
            self.seasonal_period,
        )

    @property
    def has_multiplicative_seasonality(self) -> bool:
        """Whether seasonal AR or MA factors require nonlinear estimation."""
        return bool(self.seasonal_ar_order or self.seasonal_ma_order)

    @property
    def max_lag(self) -> int:
        """Largest temporal lag after multiplicative factor expansion."""
        ar_lag = 0
        if self.ar_order and self.seasonal_ar_order:
            ar_lag = self.ar_order + self.seasonal_ar_order * self.seasonal_period
        else:
            ar_lag = max(
                self.ar_order,
                self.seasonal_ar_order * self.seasonal_period,
            )
        ma_lag = 0
        if self.ma_order and self.seasonal_ma_order:
            ma_lag = self.ma_order + self.seasonal_ma_order * self.seasonal_period
        else:
            ma_lag = max(
                self.ma_order,
                self.seasonal_ma_order * self.seasonal_period,
            )
        return max(ar_lag, ma_lag)

    def _parameter_names(self, weights: SpatialWeights) -> tuple[str, ...]:
        names: list[str] = []
        if self.include_intercept:
            names.append("intercept")
        for temporal_lag in range(1, self.ar_order + 1):
            for spatial_name in weights.names:
                names.append(f"ar.t{temporal_lag}.{spatial_name}")
        for seasonal_index in range(1, self.seasonal_ar_order + 1):
            temporal_lag = seasonal_index * self.seasonal_period
            for spatial_name in weights.names:
                names.append(f"sar.t{temporal_lag}.{spatial_name}")
        for temporal_lag in range(1, self.ma_order + 1):
            for spatial_name in weights.names:
                names.append(f"ma.t{temporal_lag}.{spatial_name}")
        for seasonal_index in range(1, self.seasonal_ma_order + 1):
            temporal_lag = seasonal_index * self.seasonal_period
            for spatial_name in weights.names:
                names.append(f"sma.t{temporal_lag}.{spatial_name}")
        return tuple(names)

    def _split_params(
        self,
        params: FloatArray,
        *,
        n_spatial: int,
    ) -> tuple[float, FloatArray, FloatArray, FloatArray, FloatArray]:
        cursor = 0
        intercept = 0.0
        if self.include_intercept:
            intercept = float(params[0])
            cursor = 1

        ar_size = self.ar_order * n_spatial
        ar = params[cursor : cursor + ar_size].reshape(self.ar_order, n_spatial)
        cursor += ar_size

        sar_size = self.seasonal_ar_order * n_spatial
        sar = params[cursor : cursor + sar_size].reshape(
            self.seasonal_ar_order, n_spatial
        )
        cursor += sar_size

        ma_size = self.ma_order * n_spatial
        ma = params[cursor : cursor + ma_size].reshape(self.ma_order, n_spatial)
        cursor += ma_size

        sma_size = self.seasonal_ma_order * n_spatial
        sma = params[cursor : cursor + sma_size].reshape(
            self.seasonal_ma_order, n_spatial
        )
        return intercept, ar, sar, ma, sma

    def _operators(
        self,
        params: FloatArray,
        weights: SpatialWeights,
    ) -> tuple[float, tuple[LagOperator, ...], tuple[LagOperator, ...]]:
        intercept, ar, sar, ma, sma = self._split_params(params, n_spatial=len(weights))
        ar_terms = expand_multiplicative_operators(
            ar,
            sar,
            weights,
            seasonal_period=self.seasonal_period,
            kind="ar",
        )
        ma_terms = expand_multiplicative_operators(
            ma,
            sma,
            weights,
            seasonal_period=self.seasonal_period,
            kind="ma",
        )
        return intercept, ar_terms, ma_terms

    def _evaluate(
        self,
        params: FloatArray,
        data: FloatArray,
        weights: SpatialWeights,
    ) -> tuple[FloatArray, FloatArray]:
        intercept, ar_terms, ma_terms = self._operators(params, weights)
        conditional_lag = max(
            maximum_operator_lag(ar_terms),
            maximum_operator_lag(ma_terms),
        )
        fitted = np.full_like(data, np.nan, dtype=float)
        residuals = np.zeros_like(data, dtype=float)
        for time_index in range(conditional_lag, data.shape[0]):
            value = np.full(data.shape[1], intercept, dtype=float)
            for operator in ar_terms:
                value += operator.matrix @ data[time_index - operator.lag]
            for operator in ma_terms:
                value += operator.matrix @ residuals[time_index - operator.lag]
            fitted[time_index] = value
            residuals[time_index] = data[time_index] - value
        return fitted, residuals

    def _objective(
        self,
        params: FloatArray,
        data: FloatArray,
        weights: SpatialWeights,
    ) -> FloatArray:
        _, residuals = self._evaluate(params, data, weights)
        vector = residuals[self.max_lag :].reshape(-1)
        if self.ridge == 0:
            return np.asarray(vector, dtype=float)
        penalty_params = params[1:] if self.include_intercept else params
        penalty = np.sqrt(self.ridge) * penalty_params
        return np.concatenate((vector, penalty))

    def _initial_params(
        self,
        data: FloatArray,
        weights: SpatialWeights,
    ) -> FloatArray:
        n_spatial = len(weights)
        n_params = (
            int(self.include_intercept)
            + (self.ar_order + self.seasonal_ar_order) * n_spatial
            + (self.ma_order + self.seasonal_ma_order) * n_spatial
        )
        params = np.zeros(n_params, dtype=float)

        rows: list[FloatArray] = []
        targets: list[FloatArray] = []
        for time_index in range(self.max_lag, data.shape[0]):
            columns: list[FloatArray] = []
            if self.include_intercept:
                columns.append(np.ones(data.shape[1], dtype=float))
            for temporal_lag in range(1, self.ar_order + 1):
                columns.extend(
                    matrix @ data[time_index - temporal_lag] for matrix in weights
                )
            for seasonal_index in range(1, self.seasonal_ar_order + 1):
                temporal_lag = seasonal_index * self.seasonal_period
                columns.extend(
                    matrix @ data[time_index - temporal_lag] for matrix in weights
                )
            if columns:
                rows.append(np.column_stack(columns))
                targets.append(data[time_index])

        direct_size = (
            int(self.include_intercept)
            + (self.ar_order + self.seasonal_ar_order) * n_spatial
        )
        if rows and direct_size:
            design = np.vstack(rows)
            target = np.concatenate(targets)
            direct, *_ = np.linalg.lstsq(design, target, rcond=None)
            params[:direct_size] = direct
        return params

    def _fit_linear_core(
        self,
        data: FloatArray,
        weights: SpatialWeights,
    ) -> STARMAResult:
        model = STARMA(
            ar_order=self.ar_order,
            ma_order=self.ma_order,
            include_intercept=self.include_intercept,
            max_iter=self.max_iter,
            tol=self.tol,
            ridge=self.ridge,
        )
        result = model.fit(data, weights)
        self.core_model_ = model
        self._internal_residuals = (
            None
            if model._internal_residuals is None
            else model._internal_residuals.copy()
        )
        return result

    def fit(self, data: Any, weights: Any) -> STARMAResult:
        """Fit the model and return inference on the transformed scale."""
        observations = validate_time_space(data)
        transformed, state = combined_difference(
            observations,
            ordinary_order=self.integration_order,
            seasonal_order=self.seasonal_integration_order,
            seasonal_period=self.seasonal_period,
        )
        resolved_weights = coerce_weights(weights, n_locations=transformed.shape[1])
        if transformed.shape[0] <= self.max_lag + 1:
            raise ValueError(
                "data contain too few time observations after differencing "
                "for the expanded seasonal model order"
            )

        self.optimization_result_ = None
        self.core_model_ = None
        if not self.has_multiplicative_seasonality:
            result = self._fit_linear_core(transformed, resolved_weights)
        else:
            initial = self._initial_params(transformed, resolved_weights)
            solution = least_squares(
                self._objective,
                initial,
                args=(transformed, resolved_weights),
                method="trf",
                ftol=self.tol,
                xtol=self.tol,
                gtol=self.tol,
                max_nfev=self.max_iter,
                x_scale="jac",
            )
            params = np.asarray(solution.x, dtype=float)
            fitted, residuals = self._evaluate(params, transformed, resolved_weights)
            residual_vector = residuals[self.max_lag :].reshape(-1)
            n_observations = int(residual_vector.size)
            n_params = int(params.size)
            degrees_of_freedom = max(1, n_observations - n_params)
            sum_squared = float(residual_vector @ residual_vector)
            sigma2 = sum_squared / degrees_of_freedom

            jacobian = np.asarray(solution.jac, dtype=float)[:n_observations]
            covariance = sigma2 * np.linalg.pinv(jacobian.T @ jacobian)
            standard_errors = np.sqrt(np.clip(np.diag(covariance), 0.0, np.inf))
            with np.errstate(divide="ignore", invalid="ignore"):
                t_values = params / standard_errors
            p_values = 2.0 * stats.t.sf(np.abs(t_values), df=degrees_of_freedom)

            public_residuals = np.full_like(transformed, np.nan, dtype=float)
            public_residuals[self.max_lag :] = residuals[self.max_lag :]
            residual_matrix = residuals[self.max_lag :]
            innovation_covariance = np.atleast_2d(
                np.cov(residual_matrix, rowvar=False, ddof=1)
            ).astype(float)
            sigma2_ml = max(sum_squared / n_observations, np.finfo(float).tiny)
            log_likelihood = (
                -0.5 * n_observations * (np.log(2.0 * np.pi * sigma2_ml) + 1.0)
            )
            aic = -2.0 * log_likelihood + 2.0 * n_params
            bic = -2.0 * log_likelihood + np.log(n_observations) * n_params
            result = STARMAResult(
                params=params,
                parameter_names=self._parameter_names(resolved_weights),
                standard_errors=np.asarray(standard_errors, dtype=float),
                t_values=np.asarray(t_values, dtype=float),
                p_values=np.asarray(p_values, dtype=float),
                fitted_values=fitted,
                residuals=public_residuals,
                innovation_covariance=innovation_covariance,
                sigma2=float(sigma2),
                log_likelihood=float(log_likelihood),
                aic=float(aic),
                bic=float(bic),
                n_observations=n_observations,
                degrees_of_freedom=degrees_of_freedom,
                converged=bool(solution.success),
                n_iterations=int(solution.nfev),
                method="nonlinear conditional least squares (seasonal)",
                conditional_lag=self.max_lag,
            )
            self.optimization_result_ = solution
            self._internal_residuals = residuals.copy()

        self.result_ = result
        self.weights_ = resolved_weights
        self.data_ = observations.copy()
        self.transformed_data_ = transformed.copy()
        self.differencing_state_ = state
        return result

    def predict_differenced(self, steps: int = 1) -> FloatArray:
        """Forecast on the highest ordinary-seasonal difference scale."""
        steps = validate_nonnegative_int(steps, name="steps")
        if steps == 0:
            raise ValueError("steps must be positive")
        if self.result_ is None or self.transformed_data_ is None:
            raise RuntimeError("fit must be called before predict")
        if self.core_model_ is not None:
            return self.core_model_.predict(steps=steps)
        if self.weights_ is None or self._internal_residuals is None:
            raise RuntimeError("fit must be called before predict")

        intercept, ar_terms, ma_terms = self._operators(
            self.result_.params, self.weights_
        )
        history = [row.copy() for row in self.transformed_data_]
        innovations = [row.copy() for row in self._internal_residuals]
        forecasts: list[FloatArray] = []
        for _ in range(steps):
            value = np.full(self.weights_.n_locations, intercept, dtype=float)
            for operator in ar_terms:
                value += operator.matrix @ history[-operator.lag]
            for operator in ma_terms:
                value += operator.matrix @ innovations[-operator.lag]
            forecasts.append(value)
            history.append(value)
            innovations.append(np.zeros_like(value))
        return np.vstack(forecasts)

    def predict(self, steps: int = 1) -> FloatArray:
        """Forecast recursively and restore the original observation scale."""
        if self.differencing_state_ is None:
            raise RuntimeError("fit must be called before predict")
        differenced = self.predict_differenced(steps=steps)
        return self.differencing_state_.inverse_forecast(differenced)
